spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: app_user
    password: o&#x7GpX7862*8tZ*VQc
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  messages:
    basename: messages

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  profiles:
    active: prod

#jwt:
#  expiration: 360000
#  secret: MyStrongSecret
#
#rsa:
#  private-key: classpath:certs/private.pem
#  public-key: classpath:certs/public.pem

client.origin: http://localhost:3000

logging:
  level:
    root: WARN
    org:
      springframework:
        jdbc:
          core: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
        security:
          oauth2: TRACE


springdoc:
  swagger-ui:
    csrf:
      enabled: false

