spring:
  liquibase:
    enabled: true # true false
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: app_user
    password: o&#x7GpX7862*8tZ*VQc
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    rest:
      default-page-size: 10
      max-page-size: 100
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate  #  validate update
    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: messages

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.gmail.com
    username: username@gmail.com
    password: XXXXXXXXXXXXXXXXXX
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'

  profiles:
    active: prod

client.origin: http://localhost:3000

app:
  image:
    bucket: /files/image
logging:
  level:
    root: ERROR
#    org:
#      springframework:
#        jdbc:
#          core: DEBUG
#        web:
#          filter:
#            CommonsRequestLoggingFilter: TRACE
#        security:
#          oauth2: TRACE

springdoc:
  swagger-ui:
    csrf:
      enabled: false

